---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list: ["recipe[nis]"]
    attributes:
      nis:
        domain: 'csd.uwo.ca'
        servers:
          - hostname: 'chaplin.csd.uwo.ca'
            ip: '129.100.16.252'
  - name: restricted_access
    run_list: ["recipe[nis]"]
    attributes:
      nis:
        domain: 'csd.uwo.ca'
        restricted_to: ['jshantz4','@Usysgrp']
        servers:
          - hostname: 'chaplin.csd.uwo.ca'
            ip: '129.100.16.252'
      shells:
        symlinks:
          "/local/bash": "/bin/bash"
          "/local/sh": "/bin/sh"
          "/local/tcsh": "/bin/tcsh"
          "/usr/local/bin/bash": "/bin/bash"
          "/usr/local/bin/tcsh": "/bin/tcsh"
          "/usr/shells/bash": "/bin/bash"
          "/usr/shells/csh": "/bin/csh"
          "/usr/shells/sh": "/bin/sh"
          "/usr/shells/tcsh": "/bin/tcsh"