---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list: ["recipe[nsswitch]"]
    attributes:
      nsswitch:
        passwd: files passwdtest
        group: files grouptest
        shadow: files shadowtest
        hosts: files dns hoststest
        networks: files networkstest
        protocols: db files protocolstest
        services: db files servicestest
        ethers: db files etherstest
        rpc: db files rpctest
        netgroup: nis netgrouptest
        automount: files automounttest
        aliases: files aliasestest
