name             'nsswitch'
maintainer       'Jeff Shantz'
maintainer_email 'Western University'
license          'Apache 2.0'
description      'Manages the Name Service Switch (/etc/nsswitch.conf).'
long_description 'Manages the Name Service Switch (/etc/nsswitch.conf).'
version          '0.1.0'

supports 'ubuntu', '>= 12.04'
supports 'centos', '>= 6.5'