---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-16.04
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-7.2
- name: centos-6.7
- name: centos-5.9

suites:
- name: default
  run_list:
    - recipe[authconfig::default]
